Change loading of OVAL result reports
OpenSCAP/openscap-report pull request #140
Opened 2023-03-08 13:44 UTC by Honny1

This PR changes the approach of loading the OVAL results report and brings special logic to determine where is present the OVAL result report with the OVAL definitions that are used in the CPE dictionary and CPE AL. 

The OVAL result report element is selected according to the references in the rule results. The selected element is the one that is not referenced in the rule results. If multiple reports are not referenced in the rule result, the element with the lower ID is selected. OVAL result reports have an ID in the format `ovalN`, where `N` is an integer. This method works if the ID format does not change over time.

2023-04-11 11:30 UTC, evgenyz requested changes

2023-04-11 11:30 UTC, evgenyz commented on openscap_report/scap_results_parser/parsers/rule_parser.py
> +            rule.oval_definition_id = check_name
The method is a 'getter', but it *sometimes* mutates the object. On top of that, it is a **static** *private* method. That's very confusing.

2023-04-11 11:30 UTC, evgenyz commented on openscap_report/scap_results_parser/scap_results_parser.py
> +    def _get_oval_definition_reference(rules):
That should be either `references` or `reference_list`.

2023-04-11 11:30 UTC, evgenyz commented on openscap_report/scap_results_parser/scap_results_parser.py
> +            self._get_applicable_cpe_ids_for_machine(report.profile_info.cpe_platforms_for_profile),
The `ProfileInfo` class already has `get_cpe_platforms_that_satisfy_evaluation_target` getter, which kinda does the same under a different name. This is inconsistent.

I'd say that `_get_applicable_cpe_ids_for_machine` should be part of `ProfileInfo` (named like `get_list_of_cpe_platforms_that_satisfy_evaluation_target`) and `get_cpe_platforms_that_satisfy_evaluation_target` should use it to join a list into a string.

2023-04-11 11:30 UTC, evgenyz commented on openscap_report/scap_results_parser/oval_and_cpe_tree_builder.py
> +            " for CPE checks. The results of the OVAL definition in the CPE checks could "
Make the way you split strings consistent: space either goes to the end or to the start of the line.

2023-04-11 11:30 UTC, evgenyz commented on openscap_report/scap_results_parser/oval_and_cpe_tree_builder.py
> +                     " the OVAL definition (\"%s\")."),
Make the way you split strings consistent: space either goes to the end or to the start of the line.

2023-04-12 12:55 UTC, Honny1 commented
Changes:
- Consistently split strings
- Reworked _get_oval_check_href method
- Renamed _get_oval_definition_reference method to _get_oval_definition_references
- The _get_applicable_cpe_ids_for_machine method has been moved to ProfileInfo
- Renamed _get_applicable_cpe_ids_for_machine method to get_list_of_cpe_platforms_that_satisfy_evaluation_target

2023-04-12 17:57 UTC, merged